export const GET_ALL_STORIES_LOAD = 'GET_ALL_STORIES_LOAD';
export const GET_ALL_STORIES_SUCCESS = 'GET_ALL_STORIES_SUCCESS';
export const GET_ALL_STORIES_FAIL = 'GET_ALL_STORIES_FAIL';

export const GET_SEARCH_POSTS = 'GET_SEARCH_POSTS';